/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sample.beam.df.shared;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmpBadge extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2794627446693151367L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmpBadge\",\"namespace\":\"com.sample.beam.df.shared\",\"fields\":[{\"name\":\"id\",\"type\":[\"int\",\"null\"]},{\"name\":\"badgein\",\"type\":[\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmpBadge> ENCODER =
      new BinaryMessageEncoder<EmpBadge>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmpBadge> DECODER =
      new BinaryMessageDecoder<EmpBadge>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EmpBadge> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EmpBadge> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmpBadge>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EmpBadge to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EmpBadge from a ByteBuffer. */
  public static EmpBadge fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Integer id;
  @Deprecated public java.lang.Integer badgein;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmpBadge() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param badgein The new value for badgein
   */
  public EmpBadge(java.lang.Integer id, java.lang.Integer badgein) {
    this.id = id;
    this.badgein = badgein;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return badgein;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: badgein = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'badgein' field.
   * @return The value of the 'badgein' field.
   */
  public java.lang.Integer getBadgein() {
    return badgein;
  }

  /**
   * Sets the value of the 'badgein' field.
   * @param value the value to set.
   */
  public void setBadgein(java.lang.Integer value) {
    this.badgein = value;
  }

  /**
   * Creates a new EmpBadge RecordBuilder.
   * @return A new EmpBadge RecordBuilder
   */
  public static com.sample.beam.df.shared.EmpBadge.Builder newBuilder() {
    return new com.sample.beam.df.shared.EmpBadge.Builder();
  }

  /**
   * Creates a new EmpBadge RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmpBadge RecordBuilder
   */
  public static com.sample.beam.df.shared.EmpBadge.Builder newBuilder(com.sample.beam.df.shared.EmpBadge.Builder other) {
    return new com.sample.beam.df.shared.EmpBadge.Builder(other);
  }

  /**
   * Creates a new EmpBadge RecordBuilder by copying an existing EmpBadge instance.
   * @param other The existing instance to copy.
   * @return A new EmpBadge RecordBuilder
   */
  public static com.sample.beam.df.shared.EmpBadge.Builder newBuilder(com.sample.beam.df.shared.EmpBadge other) {
    return new com.sample.beam.df.shared.EmpBadge.Builder(other);
  }

  /**
   * RecordBuilder for EmpBadge instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmpBadge>
    implements org.apache.avro.data.RecordBuilder<EmpBadge> {

    private java.lang.Integer id;
    private java.lang.Integer badgein;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sample.beam.df.shared.EmpBadge.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.badgein)) {
        this.badgein = data().deepCopy(fields()[1].schema(), other.badgein);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmpBadge instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sample.beam.df.shared.EmpBadge other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.badgein)) {
        this.badgein = data().deepCopy(fields()[1].schema(), other.badgein);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.sample.beam.df.shared.EmpBadge.Builder setId(java.lang.Integer value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.sample.beam.df.shared.EmpBadge.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'badgein' field.
      * @return The value.
      */
    public java.lang.Integer getBadgein() {
      return badgein;
    }

    /**
      * Sets the value of the 'badgein' field.
      * @param value The value of 'badgein'.
      * @return This builder.
      */
    public com.sample.beam.df.shared.EmpBadge.Builder setBadgein(java.lang.Integer value) {
      validate(fields()[1], value);
      this.badgein = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'badgein' field has been set.
      * @return True if the 'badgein' field has been set, false otherwise.
      */
    public boolean hasBadgein() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'badgein' field.
      * @return This builder.
      */
    public com.sample.beam.df.shared.EmpBadge.Builder clearBadgein() {
      badgein = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmpBadge build() {
      try {
        EmpBadge record = new EmpBadge();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.badgein = fieldSetFlags()[1] ? this.badgein : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmpBadge>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmpBadge>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmpBadge>
    READER$ = (org.apache.avro.io.DatumReader<EmpBadge>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
