/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sample.beam.df.shared;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmpDept extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 301562089176664922L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmpDept\",\"namespace\":\"com.sample.beam.df.shared\",\"fields\":[{\"name\":\"deptno\",\"type\":[\"string\",\"null\"]},{\"name\":\"joindate\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmpDept> ENCODER =
      new BinaryMessageEncoder<EmpDept>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmpDept> DECODER =
      new BinaryMessageDecoder<EmpDept>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EmpDept> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EmpDept> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmpDept>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EmpDept to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EmpDept from a ByteBuffer. */
  public static EmpDept fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence deptno;
  @Deprecated public org.joda.time.LocalDate joindate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmpDept() {}

  /**
   * All-args constructor.
   * @param deptno The new value for deptno
   * @param joindate The new value for joindate
   */
  public EmpDept(java.lang.CharSequence deptno, org.joda.time.LocalDate joindate) {
    this.deptno = deptno;
    this.joindate = joindate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deptno;
    case 1: return joindate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      DATE_CONVERSION,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deptno = (java.lang.CharSequence)value$; break;
    case 1: joindate = (org.joda.time.LocalDate)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'deptno' field.
   * @return The value of the 'deptno' field.
   */
  public java.lang.CharSequence getDeptno() {
    return deptno;
  }

  /**
   * Sets the value of the 'deptno' field.
   * @param value the value to set.
   */
  public void setDeptno(java.lang.CharSequence value) {
    this.deptno = value;
  }

  /**
   * Gets the value of the 'joindate' field.
   * @return The value of the 'joindate' field.
   */
  public org.joda.time.LocalDate getJoindate() {
    return joindate;
  }

  /**
   * Sets the value of the 'joindate' field.
   * @param value the value to set.
   */
  public void setJoindate(org.joda.time.LocalDate value) {
    this.joindate = value;
  }

  /**
   * Creates a new EmpDept RecordBuilder.
   * @return A new EmpDept RecordBuilder
   */
  public static com.sample.beam.df.shared.EmpDept.Builder newBuilder() {
    return new com.sample.beam.df.shared.EmpDept.Builder();
  }

  /**
   * Creates a new EmpDept RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmpDept RecordBuilder
   */
  public static com.sample.beam.df.shared.EmpDept.Builder newBuilder(com.sample.beam.df.shared.EmpDept.Builder other) {
    return new com.sample.beam.df.shared.EmpDept.Builder(other);
  }

  /**
   * Creates a new EmpDept RecordBuilder by copying an existing EmpDept instance.
   * @param other The existing instance to copy.
   * @return A new EmpDept RecordBuilder
   */
  public static com.sample.beam.df.shared.EmpDept.Builder newBuilder(com.sample.beam.df.shared.EmpDept other) {
    return new com.sample.beam.df.shared.EmpDept.Builder(other);
  }

  /**
   * RecordBuilder for EmpDept instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmpDept>
    implements org.apache.avro.data.RecordBuilder<EmpDept> {

    private java.lang.CharSequence deptno;
    private org.joda.time.LocalDate joindate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sample.beam.df.shared.EmpDept.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deptno)) {
        this.deptno = data().deepCopy(fields()[0].schema(), other.deptno);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.joindate)) {
        this.joindate = data().deepCopy(fields()[1].schema(), other.joindate);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmpDept instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sample.beam.df.shared.EmpDept other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.deptno)) {
        this.deptno = data().deepCopy(fields()[0].schema(), other.deptno);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.joindate)) {
        this.joindate = data().deepCopy(fields()[1].schema(), other.joindate);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'deptno' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeptno() {
      return deptno;
    }

    /**
      * Sets the value of the 'deptno' field.
      * @param value The value of 'deptno'.
      * @return This builder.
      */
    public com.sample.beam.df.shared.EmpDept.Builder setDeptno(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.deptno = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deptno' field has been set.
      * @return True if the 'deptno' field has been set, false otherwise.
      */
    public boolean hasDeptno() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deptno' field.
      * @return This builder.
      */
    public com.sample.beam.df.shared.EmpDept.Builder clearDeptno() {
      deptno = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'joindate' field.
      * @return The value.
      */
    public org.joda.time.LocalDate getJoindate() {
      return joindate;
    }

    /**
      * Sets the value of the 'joindate' field.
      * @param value The value of 'joindate'.
      * @return This builder.
      */
    public com.sample.beam.df.shared.EmpDept.Builder setJoindate(org.joda.time.LocalDate value) {
      validate(fields()[1], value);
      this.joindate = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'joindate' field has been set.
      * @return True if the 'joindate' field has been set, false otherwise.
      */
    public boolean hasJoindate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'joindate' field.
      * @return This builder.
      */
    public com.sample.beam.df.shared.EmpDept.Builder clearJoindate() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmpDept build() {
      try {
        EmpDept record = new EmpDept();
        record.deptno = fieldSetFlags()[0] ? this.deptno : (java.lang.CharSequence) defaultValue(fields()[0], record.getConversion(0));
        record.joindate = fieldSetFlags()[1] ? this.joindate : (org.joda.time.LocalDate) defaultValue(fields()[1], record.getConversion(1));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmpDept>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmpDept>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmpDept>
    READER$ = (org.apache.avro.io.DatumReader<EmpDept>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
